Pranav2
Umesh-01/Python-Assistant pull request #61
Opened 2022-04-04 09:53 UTC by Pranavv213

Book Reader changes made

2022-04-06 08:02 UTC, Umesh-01 requested changes

2022-04-06 08:02 UTC, Umesh-01 commented on PA.py
> +            os.startfile("C:\\Users\\91954\\AppData\\Roaming\\Microsoft\\Windows\\"
```suggestion
            os.startfile("C:\\Windows\\notepad.exe")
```

2022-04-06 08:02 UTC, Umesh-01 commented on PA.py
> +                         "Start Menu\\Programs\\Accessories\\Notepad")
```suggestion
```

2022-04-06 08:02 UTC, Umesh-01 commented on PA.py
> +
```suggestion
```

2022-04-07 06:01 UTC, Pranavv213 commented
This issue is not mine. Opening notepad  is someone else issue. Plz check.
My issue was to add Book Reader feature in PA.py which I have already done and made pull request which has no merge conflicts. PLz see to it and merge my pull request for book reader.

2022-04-07 08:18 UTC, Umesh-01 commented
> This issue is not mine. Opening notepad is someone else issue. Plz check. My issue was to add Book Reader feature in PA.py which I have already done and made pull request which has no merge conflicts. PLz see to it and merge my pull request for book reader.

Yes @Pranavv213 I know that this change was made in different PR but that PR is already merged. May be you haven't pulled the changes from the main branch that's why it is showing the previous code in your branch. Now, you can make the necessary changes, and then I will merge this PR. 👍

2022-05-15 16:46 UTC, Umesh-01 reviewed
@Pranavv213 are you working on this??

2022-07-27 17:45 UTC, closed without merging